//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Identity_test_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kategori
    {
    
        public int kategoriId { get; set; }
        public string navn { get; set; }
    
        public virtual ICollection<Oppslag> Oppslag { get; set; }
    }
}
