//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Identity_test_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kommentar
    {
        public int kommentarId { get; set; }
        public string tekst { get; set; }
        public System.DateTime dato { get; set; }

        //public int oppslagId { get; set; }
        public virtual MyUser eier { get; set; }
        public virtual Oppslag oppslag { get; set; }
    }
}
