//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Identity_test_1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Oppslag
    {
        public int oppslagId { get; set; }
        public string tittel { get; set; }
        public string ingress { get; set; }
        public string oppslagTekst { get; set; }
        public Nullable<System.DateTime> dato { get; set; }
        public Nullable<int> treff { get; set; }
        public string imageUrl { get; set; }
        public string videoUrl { get; set; }


        //public int kategoriId { get; set; }
        public virtual kategori kategori { get; set; }
        public virtual ICollection<kommentar> kommentarer { get; set; }
        public virtual MyUser eier { get; set; }
    }
}
