// <auto-generated />
namespace Identity_test_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class oppslagAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(oppslagAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201409091343387_oppslagAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
